### ISSUE TITLE
[Question] env file handling per different environments

### ISSUE THREAD

**Issue by jeffminsungkim** [nestjsx/nestjs-config#127]
**Issue type:**

- [x] question
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

**nestjs-config version**
`1.4.0`

**@nestjs/common+core or other package versions**
 - @nestjs/common: 
 - @nestjs/core: 

#### Excepted behavior

**npm run start:staging command should load staging.env file not .env**
`"start:staging": "npm run prestart:prod && NODE_ENV=staging node dist/main.js",`

**By default the package look for a .env file**
`"start:dev": "..." "`

#### Actual behavior or outcome (for issue)

`Argument of type '{ path: string; }' is not assignable to parameter of type 'string'.ts(2345)`

#### Replication/Example
I've just copied the [code snippet](https://github.com/nestjsx/nestjs-config/issues/94#issuecomment-494304674) from an issue #94 and it throws an error.
Is there any best practice to handle env files (test, staging) more like a nest way?

```ts
@Module({
  imports: [
    ConfigModule.load(path.resolve(__dirname, 'config', '**', '!(*.d).{ts,js}', {
      path: path.resolve(
        process.cwd(),
        process.env.NODE_ENV === 'staging' ? 'staging.env' : '.env'),
    })),
    DatabaseModule,
  ],
  controllers: [],
  providers: [],
})
export class AppModule { }

```

**Comment by bashleigh** [comment]
Hey! @jeffminsungkim Thanks for making a new issue! I found your error. In your path.resolve method you have added a 5th parameter with is an object. You probably missed a bracket here. 

Try this
```ts
    ConfigModule.load(
      path.resolve(__dirname, 'config', '**', '!(*.d).{ts,js}'), 
      {
        path: path.resolve(
          process.cwd(),
          process.env.NODE_ENV === 'staging' ? 'staging.env' : '.env'),
      },
    ),
```

**Comment by jeffminsungkim** [comment]
Hey, @bashleigh  Thanks for a quick response!
I believe there's no **path** parameter does not exist in type 'ConfigOptions'.

**Comment by bashleigh** [comment]
ConfigOptions extends a Partial of DotEnvConfigOptions. 

https://github.com/nestjsx/nestjs-config/blob/master/src/module/config.service.ts#L22

Are you having an issue with it?

**Comment by jeffminsungkim** [comment]
@bashleigh Yeah, I still having the same error message.

**Comment by jeffminsungkim** [comment]
One more thing @bashleigh `npm run start:staging` command does load staging.env file, but it still using .env file variables. Should I open a new issue?

```ts
/my-project-path/dist/config/**/!(*.d).{ts,js} { path: '/my-project-pathi/staging.env' }
```

**Comment by bashleigh** [comment]
@jeffminsungkim are you running this in a docker container or a local machine? When running in a docker container, the container needs to be stopped and started with the new envs

**Comment by jeffminsungkim** [comment]
First things first, I don't think this is right but, should I install `@types/dotenv` package manually before using `nestjs-config`? If so, the documentation has to be updated.

Yeah, I'm using a docker container. As I mentioned right above your comment, the issue that I'm facing it happens before running the container. Any ideas @bashleigh?

**Comment by bashleigh** [comment]
no it's cool! Keep it open. I might add a PR for this. I did close someone's PR because they never really responded why and I feel bad now! 
Thanks for the repo! I'll check it out!

**Comment by bashleigh** [comment]
checked out the repo, couldn't get your container running because it's on gcloud? :joy: so first thing I noticed was you're loading a file yet you're also using .env_file in the docker compose setup so you're defining envs in the container which you don't want to do if you're using 2 files. I 'think' the env on the system (container) takes president over file based declared envs. Not 100% sure but that could be your issue?

**Comment by jeffminsungkim** [comment]
@bashleigh For now, everything works perfectly! But, without having `@types/dotenv` package, it throws the following error. Perhaps we should fix the documentation? You have to create your own `.env.staging` file to make a Docker container runnable.

```ts
Argument of type '{ path: string; }' is not assignable
to parameter of type 'ConfigOptions'.

Object literal may only specify known properties, 
and 'path' does not exist in type 'ConfigOptions'.
```
