### ISSUE TITLE
Move to @nestjsx/config?

### ISSUE THREAD

**Issue by cookrn** [nestjsx/nestjs-config#129]
**Issue type:**

- [x] question
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

**nestjs-config version**
n/a

**@nestjs/common+core or other package versions**
n/a

#### Excepted behavior 
I'm curious if it's been considered to re-publish this package using the namespace style? Specifically, instead of `nestjs-config`, using `@nestjsx/config`? This would be more inline with the other packages managed by this Github organization.

#### Actual behavior or outcome (for issue)
n/a

#### Replication/Example
n/a

**Comment by bashleigh** [comment]
it has been considered yes :p I can't really say why we haven't yet but it's a possibility for all repos within this organisation to have the `@nestjsx` prefix instead of the `nestjs-` prefix
