### ISSUE TITLE
@types/dotenv is no longer required to be installed by users

### ISSUE THREAD

**Issue by jeffminsungkim** [nestjsx/nestjs-config#231]
**Issue type:**

- [x] question
- [ ] bug report
- [ ] feature request
- [x] documentation issue

**nestjs-config version**
1.4.5 (latest)

**@nestjs/common+core or other package versions**
 - @nestjs/common: 
 - @nestjs/core: 

#### Excepted behavior
Since Oct 16 `dotenv` package has added [@types/dotenv](https://github.com/motdotla/dotenv/pull/430). We no longer need to set the [peerDependencies](https://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html) property in the package.json which shows unnecessary warning message, as well as the README file, should be fixed.

#### Actual behavior or outcome (for issue)

> npm WARN nestjs-config@1.4.5 requires a peer of @types/dotenv@^8.2.0 but none is installed. You must install peer dependencies yourself.

#### Replication/Example

Better use dotenv types from the following path
> node_modules/dotenv/types/index.d.ts

NOT
> node_modules/nestjs-config/node_modules/dotenv/types/index.d.ts

Should I make a PR? 🤔

**Comment by bashleigh** [comment]
oooo yes please!

**Comment by jeffminsungkim** [comment]
@bashleigh I've created the PR #236
