### ISSUE TITLE
Usage in TypeORM transformer

### ISSUE THREAD

**Issue by RobertMenke** [nestjsx/nestjs-config#245]
**Issue type:**

- [x] question
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

**nestjs-config version**
1.4.5

**@nestjs/common+core or other package versions**
 - @nestjs/common: 6.10.12
 - @nestjs/core: 6.10.12

Hey, great work on this module! I have a common use case - encrypting/decrypting data when going in and out of the database using typeorm transformers:

Contrived example:
```ts
@Column({ 
    nullable: false, 
    type: 'text', 
    transformer: {
         from(value: string) {
              return decrypt(value, configService.get('privateKey'))
         },
         to(value: string) {
              return encrypt(value, configService.get('publicKey'))
         }
    }
 })
bankAccountRoutingNumber: string
```

Unfortunately, I don't believe that the transformer definitions have access to the DI container, so I have to create a separate instance of `ConfigService` for this use case only as far as I know. Is there any way to use the `ConfigService` instantiated by the DI container for TypeORM transformers?

**Comment by bashleigh** [comment]
That's a good question. I don't believe there is a method to handle this other than creating a subscriber to handle the encryption on insertion and using a getter with class-transformer to transform the value. not ideal but it would work! The alternative unfortunately is loading the dotenv config method before importing this file. Can be done by running `ConfigService.load` before importing your entities

**Comment by RobertMenke** [comment]
Ok no worries! I figured as much. I think for now I'll just continue to export a separate instance of `ConfigService` that isn't managed by DI just for the transformers. It's not really too inconvenient given that having that encrypt/decrypt operation in my tests is harmless. Feel free to close if you'd like!
