### ISSUE TITLE
Compatibility with NestJS version 7

### ISSUE THREAD

**Issue by kdi-1** [nestjsx/nestjs-config#310]
**Issue type:**

- [X] question
- [ ] bug report
- [X] feature request
- [ ] documentation issue

**nestjs-config version**
1.4.6 

**@nestjs/common+core or other package versions**
 - @nestjs/common: 7.0.7
 - @nestjs/core: 7.0.7

#### Excepted behavior 
no warning message  when install nestjs-config ``` npm i nestjs-config ```

#### Actual behavior or outcome (for issue)
``` npm WARN nestjs-config@1.4.6 requires a peer of @nestjs/common@^5.1.0 || ^6.0.3 but none is installed. You must install peer dependencies yourself. ```

#### Replication/Example

When I install nestjs-config ``` npm i nestjs-config```  I get a npm warning message as I mentioned above. Are there any plans to upgrade the lib for compatibility with NestJS version 7 ?

**Comment by pkchv** [comment]
I've created a pull request to fix this, there's no reason to not allow clean installs with latest version of `@nestjs/common` in my opinion. I know that development of this library stalled, but support for the latest version of nest is crucial for this library to be a viable option.

**Comment by madfist** [comment]
This problem is driven by npm7 auto-installing peer dependencies so it needs to enable a wider range of compatible versions in order to not having to use `-legacy-peer-deps` https://stackoverflow.com/a/66620869

**Comment by bashleigh** [comment]
https://github.com/nestjsx/nestjs-config/blob/master/package.json#L40 should solve this problem no?

**Comment by pkchv** [comment]
Yes, this is merged now.
