### ISSUE TITLE
error TS7016: Could not find a declaration file for module 'dotenv'.

### ISSUE THREAD

**Issue by bedemiralp** [nestjsx/nestjs-config#98]
**Issue type:**

- [ ] question
- [x] bug report
- [ ] feature request
- [ ] documentation issue

**nestjs-config version**
1.4.1

**@nestjs/common+core or other package versions**
 - @nestjs/common: 6.3.1
 - @nestjs/core: 6.3.1

#### Excepted behavior 
When nestjs-config is added to another project which has the `strict` flag enabled in its `tsconfig.json` file, the project fails to build.
#### Actual behavior or outcome (for issue)
The project which depends on `nestjs-config` should be built with `strict` flag enabled in `tsconfig.json`.
#### Replication/Example
* Set `strict` flag to `true` on a project which depends on `nestjs-config`.
* run `tsc`.
* tsc will return:
```
> tsc

node_modules/nestjs-config/dist/module/config.service.d.ts:1:37 - error TS7016: Could not find a declaration file for module 'dotenv'. '/Users/b/crew/nestjs-demo/terminus-test/node_modules/nestjs-config/node_modules/dotenv/lib/main.js' implicitly has an 'any' type.
  Try `npm install @types/dotenv` if it exists or add a new declaration (.d.ts) file containing `declare module 'dotenv';`

1 import { DotenvConfigOptions } from 'dotenv';
                                      ~~~~~~~~
```

```ts
```

**Comment by bashleigh** [comment]
Would you mind sharing your tsconfig please? I feel like you should be excluding node_modules from tsc. And or be including @types/dotenv in your project. I don't think this is an issue with nestjs-config.
